### ISSUE TITLE
Linux path issues

### ISSUE THREAD

**Issue by theonlyames** [denetii/io_thps_scene#1]
Currently when exporting a level on Linux backslashes are still used in the output paths. 

**No such file or directory: '/home/riha/Documents/THUG+ Levels/Levels\\LevelA/LevelA.qb'**

![**screenshot**](https://user-images.githubusercontent.com/11744820/41822902-ce99cb96-77c4-11e8-82e7-e53bdf031d62.png)

Should be a easy fix.

**Comment by denetii** [comment]
Fixed in #2
