### ISSUE TITLE
Plugin claims an upgrade to 2.8x is required, potentially old build used in 1.1.0 release

### ISSUE THREAD

**Issue by DeerTears** [denetii/io_thps_scene#13]
Using the io_thps_scene.zip found inside of the release 1.1.0 zip, the internal version of the plugin states that the io_thps_scene is still 1.0.0. Looking on other forums, it seems that this error comes up when a plugin is outdated, not when the Blender version is outdated. Did an old build get mistaken for the newest release? Are there scripts that are outdated that don't work on the current 1.1.0 release?

I'm pretty confident I got the same error message for both versions when trying to enable the plugin. Here's how the plugin appears in the plugin manager for both Blender 2.83.13 LTS and 2.91.0:

![image](https://user-images.githubusercontent.com/47726614/117239530-cfc66800-ade3-11eb-9018-9b1081a028f8.png)

Installing it brings up this message:
![image](https://user-images.githubusercontent.com/47726614/117239277-575fa700-ade3-11eb-99a9-c4ac29ae1688.png)

Curiously, I did not find either a 2.7 or a 2.8x version of the plugin when I downloaded the latest release:
![image](https://user-images.githubusercontent.com/47726614/117239762-3cd9fd80-ade4-11eb-9d52-78fc1353931d.png)

I couldn't find any other .zip files in this project's source or in the other release.

Is there a version of this plugin that matches more of what the Readme currently says? That's fine if the 2.7 version been phased out already, but I'm not sure why the current version isn't working even with 2.83.13 LTS. Any guidance is appreciated.

**Comment by DeerTears** [comment]
Oh, another Blender plugin was having the same issue and found a temporary fix, later the developer went and made a full fix: https://github.com/mtyka/attractor/issues/1

**Comment by denetii** [comment]
The last release is from 2018, before Blender 2.8x was stable. Another release is coming soon with the version for 2.8x and up (at least to 2.91). If you'd rather not wait, you can pull the latest build of the blender2.8 branch from here - just make sure the zip file and the folder contained inside are both named `io_thps_scene`.

**Comment by DeerTears** [comment]
Oh, legitimately didn't realize I could just zip up this entire repo *as* the new .zip plugin. That's where I got lost with installation. Thanks!
