### ISSUE TITLE
Unable to bake lightmaps (Blender Render)

### ISSUE THREAD

**Issue by theonlyames** [denetii/io_thps_scene#3]
I've been running into this issue and cannot for the life of me figure out what is causing it. 
Whenever I try to bake 'Lighting only' or 'Ambient Occlusion' lightmaps using the Blender Render mode, I get the following error: 

```
**Traceback (most recent call last):
  File "C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_thps_scene\bake.py", line 1003, in execute
    bake_thug_lightmaps(meshes, context)
  File "C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_thps_scene\bake.py", line 621, in bake_thug_lightmaps
    test_mat = orig_mats[orig_index]
TypeError: 'NoneType' object is not subscriptable**
```

Here's the full console log: 

> ****************************************
> BAKING LIGHTING FOR OBJECT #1 OF 1: Cube
> ****************************************
> Object lightmap resolution is: 128x128
> Resolution after scene scale is: 128x128
> Removing existing images/UV maps.
> ID user decrement error: IMLM_DAY_Cube (from '[Main]'): 0 <= 0
> PyContext 'window' not found
> PyContext 'window' not found
> 
> Starting unwrap
>         Generating lengths...done
> ...done
>         Consolidating Boxes...Consolidated 0 boxes, done
>         Packing Boxes 6...done
>         writing back UVsdone
> finished all 0.00
> Traceback (most recent call last):
>   File "C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_thps_scene\bake.py", line 1003, in execute
>     bake_thug_lightmaps(meshes, context)
>   File "C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_thps_scene\bake.py", line 621, in bake_thug_lightmaps
>     test_mat = orig_mats[orig_index]
> TypeError: 'NoneType' object is not subscriptable
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

**Comment by denetii** [comment]
Now fixed! Thanks again :)
